CREATE TABLE IF NOT EXISTS "student" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_no" varchar(255),
  "firstname" varchar(255),
  "lastname" varchar(255),
  "school" varchar(255)
);

CREATE TABLE IF NOT EXISTS "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(255),
  "password_hash" varchar(255)
);

CREATE TABLE IF NOT EXISTS "class" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subject_name" varchar(255)
);

CREATE TABLE IF NOT EXISTS "teacher_class" (
  "teacher_id" int REFERENCES "teacher" ("id"),
  "class_id" int REFERENCES "class" ("id"),
  PRIMARY KEY ("teacher_id", "class_id")
);

CREATE TABLE IF NOT EXISTS "student_class" (
  "student_id" int REFERENCES "student" ("id"),
  "class_id" int REFERENCES "class" ("id"),
  PRIMARY KEY ("student_id", "class_id")
);

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'class_session_status') THEN
    CREATE TYPE class_session_status AS ENUM ('open', 'closed');
  END IF;
END $$;

CREATE TABLE IF NOT EXISTS "class_session" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" int REFERENCES "class" ("id"),
  "teacher_id" int REFERENCES "teacher" ("id"),
  "start_time" timestamp,
  "end_time" timestamp,
  "status" class_session_status
);

CREATE TABLE IF NOT EXISTS "checkin" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" int REFERENCES "class_session" ("id"),
  "student_id" int REFERENCES "student" ("id"),
  "checkin_time" timestamp
);

CREATE UNIQUE INDEX IF NOT EXISTS "idx_checkin_session_student" ON "checkin" ("session_id", "student_id");
