CREATE TABLE "student" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_no" varchar(255),
  "firstname" varchar(255),
  "lastname" varchar(255),
  "school" varchar(255)
);

CREATE TABLE "teacher" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(255),
  "password_hash" varchar(255)
);

CREATE TABLE "teacher_class" (
  "teacher_id" int,
  "class_id" int,
  PRIMARY KEY ("teacher_id", "class_id")
);

CREATE TABLE "student_class" (
  "student_id" int,
  "class_id" int,
  PRIMARY KEY ("student_id", "class_id")
);

CREATE TABLE "class" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "subject_name" varchar(255)
);

CREATE TABLE "checkin" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" int,
  "student_id" int,
  "checkin_time" datetime
);

CREATE TABLE "class_session" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "class_id" int,
  "teacher_id" int,
  "start_time" datetime,
  "end_time" datetime,
  "status" enum(open,closed)
);

CREATE UNIQUE INDEX ON "checkin" ("session_id", "student_id");

ALTER TABLE "teacher_class" ADD FOREIGN KEY ("teacher_id") REFERENCES "teacher" ("id");

ALTER TABLE "teacher_class" ADD FOREIGN KEY ("class_id") REFERENCES "class" ("id");

ALTER TABLE "student_class" ADD FOREIGN KEY ("student_id") REFERENCES "student" ("id");

ALTER TABLE "student_class" ADD FOREIGN KEY ("class_id") REFERENCES "class" ("id");

ALTER TABLE "checkin" ADD FOREIGN KEY ("session_id") REFERENCES "class_session" ("id");

ALTER TABLE "checkin" ADD FOREIGN KEY ("student_id") REFERENCES "student" ("id");

ALTER TABLE "class_session" ADD FOREIGN KEY ("class_id") REFERENCES "class" ("id");

ALTER TABLE "class_session" ADD FOREIGN KEY ("teacher_id") REFERENCES "teacher" ("id");
